version: "2.2"
   
services:
  db:
    image: mysql:5.7
    # ports:
    #   - '3306:3306'
    environment:
      - MYSQL_DATABASE=mayurtest
      - MYSQL_USER=rootmayur
      - MYSQL_PASSWORD=rootmayur
      - MYSQL_ROOT_USER=rootmayur
      - MYSQL_ROOT_PASSWORD=rootmayur
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
